export const TYPE_QUERY_KEYS = {
  GET_LANGUAGES: 'GET_LANGUAGES',
  GET_GENRES: 'GET_GENRES',
  GET_DISCOVER_MOVIE: 'GET_DISCOVER_MOVIE',
  GET_MOVIE_BY_CATEGORY: 'GET_MOVIE_BY_CATEGORY',
  GET_MOVIE_BY_SEARCH: 'GET_MOVIE_BY_SEARCH',
  GET_POPULAR: 'GET_POPULAR',
  GET_TOP_RATED: 'GET_TOP_RATED',
  GET_UPCOMING: 'GET_UPCOMING',
  GET_NOW_PLAYING: 'GET_NOW_PLAYING',
  GET_DETAIL_MOVIE: 'GET_DETAIL_MOVIE',
};
