// import { GET_POPULAR_PRODUCTS_PARAMS } from "./defaultParam/movie";

export const TYPE_QUERY_KEYS = {
  GET_POPULAR: 'GET_POPULAR',
  GET_TOP_RATED: 'GET_TOP_RATED',
  GET_UPCOMING: 'GET_UPCOMING',
  GET_NOW_PLAYING: 'GET_NOW_PLAYING',
};
